### ISSUE TITLE
0.7 release date?

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ddogleg#2]
Is there a planned release date for the next (0.7) version? I'm trying to use ddogleg in a project, but it seems that 0.6 is not compatible with the recent versions of EJML  (>0.27).

I did get it running using the current Github sources, but an official release on maven central would be preferable.

**Comment by lessthanoptimal** [comment]
It should be released in the next 1 to 3 weeks.  There are some modifications being made to it right now for another project.  That project should have its next release soon.  FYI changes are being made to its clustering algorithms.  Everything else should be stable and not modified.

**Comment by ennerf** [comment]
Great. Thank you :+1:

**Comment by lessthanoptimal** [comment]
Released.  Plus new webpage!

**Comment by ennerf** [comment]
:+1:
