### ISSUE TITLE
Simple linear regression?

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ddogleg#24]
I need to do a simple linear regression on an array of x/y values, but the [ExampleRobustModelFit](https://github.com/lessthanoptimal/ddogleg/blob/v0.23/examples/src/org/ddogleg/example/ExampleRobustModelFit.java) example needs multiple custom classes.

Is that the way to go or is that anything simpler that works out of the box?

**Comment by ennerf** [comment]
Solved it with [PolynomialFit](https://github.com/lessthanoptimal/ejml/blob/v0.41/examples/src/org/ejml/example/PolynomialFit.java) from EJML

**Comment by lessthanoptimal** [comment]
Do you need to remove noise?

**Comment by ennerf** [comment]
I haven't tested noise removal yet, but the initial version already worked well enough for what I was looking at
