### ISSUE TITLE
Constrained least-squares

### ISSUE THREAD

**Issue by Hendekagon** [lessthanoptimal/ddogleg#5]
This isn't an issue, more of a request of advice on how to add constraints to the leastSquaresTrustRegion implementation. I'm currently doing it by applying constraints to the inputs of FunctionNtoM, and it seems to work, but this is an unfamiliar area so I'd be grateful for any things to watch out for.

**Comment by lessthanoptimal** [comment]
Posted a reply to your original message on the message board.  Sorry for taking a bit.
