### ISSUE TITLE
Missing technical report

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ddogleg#6]
I get a `404` when clicking on the [Peter Abeles, “DDogleg Technical Report: Nonlinear Optimization” Revision 2018-1](http://ddogleg.org/reports/ddogleg_optimization_2018_1.pdf) link in the DDogleg Manual on `Unconstrained Non-Linear Optimization` (http://ddogleg.org/optimization/Manual.html)

**Comment by lessthanoptimal** [comment]
I'll post that soon. was hoping to add one more feature first.
